### ISSUE TITLE
Segmentation fault?

### ISSUE THREAD

**Issue by kaanaksit** [mrever/snips#1]
Hi I am trying to create a stable thread inside blender and I found your code here as an example:

https://github.com/mrever/snips/blob/525d4faa51f9d004da6cbc18540855aa251da467/misc/blend_thread_test.py#L10

I am reaching out to ask if this is a stable example or does it also return segmentation fault in your case?

**Comment by kaanaksit** [comment]
Anyways, I believe that piece of code can never work, fix is highlighted here: https://docs.blender.org/api/current/bpy.app.timers.html

**Comment by mrever** [comment]
Never did get it to work right.  This "snips" repository is just misc. odds and ends that I either find useful or intended to work on again.

Thanks for that pointer, I'll check it out.
